USE [master]
GO
CREATE LOGIN [AAF] WITH PASSWORD='AAF', DEFAULT_DATABASE=[BDAAF], CHECK_EXPIRATION=OFF,
CHECK_POLICY=OFF
GO
USE [BDAAF]
GO
CREATE USER [AAF] FOR LOGIN [AAF]
GO
USE [BDAAF]
GO
ALTER ROLE [db_owner] ADD MEMBER [AAF]
GO